domains:
  - name: 'TRV14'
    version: '2.0.0'
    forms:
      - name: "static-form"
        url: "static-sample-form"
        path: "TRV14/static-sample-form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "dynamic-form"
        url: "dynamic-sample-form"
        path: "TRV14/dynamic-sample-form"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "additional details"
        url: "additional_details_form"
        path: "TRV14/dynamic-sample-form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "test-form"
        url: "test-sample-form"
        path: "TRV14/test-sample-form"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
  - name: 'FIS12'
    version: '2.0.2'
    forms:
      - name: "consumer_information_form"
        url: "consumer_information_form"
        path: "FIS12/consumer_information_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "consumer_information_form_1"
        url: "consumer_information_form_1"
        path: "FIS12/consumer_information_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "verification_status"
        url: "verification_status"
        path: "FIS12/verification_status"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "loan_amount_adjustment_form"
        url: "loan_amount_adjustment_form"
        path: "FIS12/loan-amount-adjustment-form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"        
      - name: "manadate_details_form"
        url: "manadate_details_form"
        path: "FIS12/manadate-details-form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"     
      - name: "Ekyc_details_form"
        url: "Ekyc_details_form"
        path: "FIS12/Ekyc_details_form"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "payment_url_form"
        url: "payment_url_form"
        path: "FIS12/payment_url_form"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "personal_loan_information_form"
        url: "personal_loan_information_form"
        path: "FIS12/personal_loan_information_form"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
  - name: 'FIS12'
    version: '2.2.1'
    forms:
      - name: "product_details_form"
        url: "product_details_form"
        path: "FIS12/product_details_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "personal_details_information_form"
        url: "personal_details_information_form"
        path: "FIS12/personal_details_information_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "down_payment_form"
        url: "down_payment_form"
        path: "FIS12/down_payment_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "manadate_details_form"
        url: "manadate_details_form"
        path: "FIS12/manadate-details-form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "Ekyc_details_verification_status"
        url: "Ekyc_details_verification_status"
        path: "FIS12/Ekyc_details_verification_status"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
  - name: 'FIS13'
    version: '2.0.1'
    forms:
      - name: "individual_information_form"
        url: "individual_information_form"
        path: "FIS13/health/individual_information_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "family_information_form"
        url: "family_information_form"
        path: "FIS13/health/family_information_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "Ekyc_details_form"
        url: "Ekyc_details_form"
        path: "FIS13/health/Ekyc_details_form"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "Proposer_Details_form"
        url: "Proposer_Details_form"
        path: "FIS13/health/Proposer_Details_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "nominee_details_form"
        url: "nominee_details_form"
        path: "FIS13/health/nominee_details_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "verification_status"
        url: "verification_status"
        path: "FIS13/health/verification_status"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "consumer_information_form"
        url: "consumer_information_form"
        path: "FIS13/health/consumer_information_form"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "vehicle_details_form"
        url: "vehicle_details_form"
        path: "FIS13/motor/vehicle_details_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "pan_details_form"
        url: "pan_details_form"
        path: "FIS13/motor/pan_details_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "personal_details_form"
        url: "personal_details_form"
        path: "FIS13/motor/personal_details_form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "vehicle_nominee_details_Form"
        url: "vehicle_nominee_details_Form"
        path: "FIS13/motor/vehicle_nominee_details_Form"
        type: "static"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
      - name: "manual_review_form"
        url: "manual_review_form"
        path: "FIS13/motor/manual_review_form"
        type: "dynamic"
        sessionUpdateFunction: "update-session.ts"
        successRedirect: "https://example.com/success"
  
